### ISSUE TITLE
Setting url on o-image component

### ISSUE THREAD

**Issue by jon-blanco-imatia** [OntimizeWeb/ontimize-web-ngx#1091]
### What is the current behavior?
When modifying the o-image data value on a subscription with a new url (with [data] parameter pointing to a variable that changes), it doesn't show the image properly. The component concatenates before the url the following string: "data:image/*;base64,https..." and gets a HTTP error trying to fetch the image. The value of the component is correct, but as 'src' stores the concatenated url and prays for not be modified due to security reasons.

### Steps to reproduce
Change the data value of the component inside a subscription with an url storing an image

### Affected versions:
- `ontimize-web-ngx`: "^8.5.10"

### Additional context
The url is 'https'

**Comment by patricia-martinez-imatia** [comment]
This is a completed in milestone `8.10.0`
