### ISSUE TITLE
Ellipsis disapear in columns with tooltip after navigation

### ISSUE THREAD

**Issue by jaimepineiro** [OntimizeWeb/ontimize-web-ngx#1158]
### What is the current behavior?
First time that a table with one column with tooltip="true" is displayed, ellipsis is shown but after navigating to another transaction and go back, ellipsis disappear, see attached screenshots:
![antes](https://user-images.githubusercontent.com/45460679/217265038-ebe31d19-af70-46f6-9b96-b858da07f8cb.png)
![despues](https://user-images.githubusercontent.com/45460679/217265103-8e12e633-e1c7-40ad-83d2-6a02e12a76e7.png)

### Steps to reproduce
1. Enter in a transaction with an ontimize table with a column having tooltip="true" 
2. Navigate to another transaction
3. Return to first transaction

### Affected versions:
- `ontimize-web-ngx`: 8.10.0

**Comment by patricia-martinez-imatia** [comment]
The issue is closed because we did not reproduce the bug
