### ISSUE TITLE
o-checkbox stays disabled if it is initialized with enabled=false even after enabled being changed to true

### ISSUE THREAD

**Issue by raul-carricoba-imatia** [OntimizeWeb/ontimize-web-ngx#1188]
### What is the current behavior?
If an o-checkbox component is initialized with enabled set to false even after it being changed to true it will stay disabled.

### Steps to reproduce
Set enabled="false" inside the o-checkbox in the html file, then use @ViewChild to access it and either use setEnabled(true) or .enabled = true. I also tried it with a control var enabled="{{var}}" and changing its value from initially false to true. To ensure the component was initialized when I changed the enabled value all changes were made inside the onDataLoaded of the o-form containing the o-checkbox. The component always stayed disabled.

The other way around, starting with enabled="true" and then changing it to false works without a problem.

### Affected versions:
- `ontimize-web-ngx`: 8.10.0

**Comment by patricia-martinez-imatia** [comment]
The same bug happens in all ontimize inputs

**Comment by patricia-martinez-imatia** [comment]
Resolved in  milestone: 8.11.2
