### ISSUE TITLE
The o-date-input component validator not work with value-type distinct string

### ISSUE THREAD

**Issue by juanjo-alvarez** [OntimizeWeb/ontimize-web-ngx#1238]
### What is the current behavior?
The ontimize component o-date-input not validate dates with min and max if the value-type is other than string or skip the attribute of value-type in the tag

### Steps to reproduce
create a o-date-input tag and skip the attribute value-type or put the value-type date

### Affected versions:
- `ontimize-web-ngx`: ^8.12.1

### Additional context
review the playground of ontimize for this component, the format is LL in the code but in the view use only L, and the code not have the value-type attribute

**Comment by juanjo-alvarez** [comment]
The documentation at https://ontimizeweb.github.io/docs/v8/components/input/date/api is wrong, the max and min attributes works with TIMESTAMP data type and in the documentation shows String.

**Comment by gonzalo-martinez-imt** [comment]
This bug will be solved updating the documentation (https://github.com/OntimizeWeb/docs/issues/404) and adding more examples to the playground (https://github.com/OntimizeWeb/ontimize-web-ngx-playground/issues/244)
