### ISSUE TITLE
O-list: customize add event

### ISSUE THREAD

**Issue by dr-mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ngx#128]
The idea is to give the user the possibility to specify the action of the add button:

Example: add event to o-list on clicking on the add button: (onAdd)="onAddToList($event)"

**Client side:**
```
onAddToList(e){
   console.log(e);
}
```

**Comment by gonzalo-martinez-imt** [comment]
Resolving duplicated issue in https://github.com/OntimizeWeb/ontimize-web-ngx/issues/134
