### ISSUE TITLE
[Feature request] Inputs right icons should be hidden when enabled="false"

### ISSUE THREAD

**Issue by dr-mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ngx#137]
## # I'm submitting a...
[X ] Feature request
## # Current behavior
The input are showing the icons at the right with grey color.
## # Expected behavior
Inputs right icons should be hidden when enabled="false".
## # Motivation 
- It is confusing when icons are shown+disabled it may be editable field
- Reducing the number of elements in a form
## # Environment
Angular version: 4.3.6
[ X] Chrome (desktop)

**Comment by daniel-grana** [comment]
This is the standard behaviour and it is not going to be implemented in the library. If you want this funcitionality you should implement in your code.
