### ISSUE TITLE
[Bug report] O-Form inside a md-dialog

### ISSUE THREAD

**Issue by dr-mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ngx#141]
## I'm submitting a
[X] Bug report

## Current behavior
When try to define o-form inside an md-dialog-content is provoking an error in the method addDeactivateGuard of OFormComponent:

> `Cannot read property 'canDeactivate' of null`
> `OFormComponent.addDeactivateGuard (o-form.component.js:328)`

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [ X] Chrome

For Tooling issues:
- Node version: v6.11.0
- Platform:  Windows
</code></pre>

**Comment by manu-cr** [comment]
Fixed in [26a0e04](https://github.com/OntimizeWeb/ontimize-web-ngx/commit/26a0e04)
