### ISSUE TITLE
[Feature request] O-table inline edition via a Data Service

### ISSUE THREAD

**Issue by dr-mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ngx#144]
## I'm submitting a
[ X] Feature request

## Expected behavior
The table component , in case of having it configured to use a data service (service and entity), should be able to support inline edit of text, number, combo, list (depending on the type of the edited cell)

[Demo](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B3mOPoJlxiFhZkY4b1VkME5QcXM/components-datatables-interaction-editing3.png)

## What is the motivation?
The table should have an attribute that enables on-the-fly update in server-side. Thus by having a service and entity defined, user will be able to edit directly in the table without need to access to the row detail form in order to edit its fields (it is easier to edit directly in the table than opening the row in a form). When the 'editable-columns' are defined and "edit-in-row" is enabled, this feature is enabled which allows, after editing in the desired cell, push and update the data in the server using the data service configuration.

## Environment

<pre><code>
Angular version: 4.3.6
Ontimize-web version: 2.1.0-rc.1

Browser:
- [X] Chrome

For Tooling issues:
- Node version: v6.11.0
- Platform:  Windows
</code></pre>

**Comment by manu-cr** [comment]
Use a table cell editor to modify the content of a table cell. Check the docs [here](https://ontimizeweb.github.io/docs/components/table/#editing)
