### ISSUE TITLE
Bug on <o-table-cell-editor-boolean> when boolean type is number

### ISSUE THREAD

**Issue by cfvillar** [OntimizeWeb/ontimize-web-ngx#154]
## I'm submitting a...

[ ] Bug report 
The boolean editor doesn't work properly when dealing with numbers

## Current behavior
If we have a <o-table-cell-editor-boolean> working against a boolean-type=number there's a problem with the inner value change, as it changes between true/false instead of 1/0.
So, if we have a renderer with boolean-type=number it won't be properly drawn as it won't understand the true/false inner value

                <o-table-column attr="applied" title="applied">
                        <o-table-cell-renderer-boolean boolean-type="number" 
                                        true-value-type="icon" true-value="done" 
                                        false-value-type="icon" false-value="crop_square">
                        </o-table-cell-renderer-boolean>
                        <o-table-cell-editor-boolean boolean-type="number">
                        </o-table-cell-editor-boolean>
                </o-table-column>

## Expected behavior
When the editor has boolean-type=number, the inner value whould vary between 0 and 1

**Comment by gatsbimantico** [comment]
Seems like all the returned values in `parseValueByType` were booleans despite the method said to return `any`.

I created a pull request that splits the different parsing logic making the types more specific and making the type number to return a number as suggested.

**Comment by gatsbimantico** [comment]
@cfvillar A fix was merged for this, can you provide feedback if it's working for you and close the issue?

I guess the same kind of fix is required for the type string, as it's currently returning a boolean instead of a string.
