### ISSUE TITLE
o-file-input. File type acceptance in MAC

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#1567]
### What is the current behavior?
If you set accept-file-type=".*", in a MAC device it is not recognized. However it works on Windows. Maybe it is a wrong pattern definition and not a bug.

- `ontimize-web-ngx`: 8.2.5

**Comment by tomfacal** [comment]
Resolves with */* as accept-file-type.
