### ISSUE TITLE
stay-in-record-after-insert action fails after new module routing

### ISSUE THREAD

**Issue by cfvillar** [OntimizeWeb/ontimize-web-ngx#157]
## I'm submitting a...
<pre><code>
[X ] Bug report  
</code></pre>

## Current behavior
We have:
* Module A: "asset-types" -> [HOME]/administration/asset-manager/
* Module B: "assetrelation" which is called from Module A via button:
<pre>
	openAssetRelations() {
		this.router.navigate(['assetrelation'],
			{
				relativeTo: this.actRoute
			}
		)
	}
</pre>

Routing in module A is defined as 
<pre>
const routes: Routes = [
  { path: '', component: ItemtypesHomeComponent },
  { path: 'assetall', loadChildren: loadAssetsAllModule },
  { path: 'assetrelation', loadChildren: loadAssetRelationModule },
</pre>

Module B starts with a home component that's just a table with URL:
_[HOME]/administration/asset-manager/assetrelation_

Now we insert a new element in the table:
* If the form has the stay-in-record-after-insert parameter, the returning URL is:
[HOME]/administration/asset-manager/{new-id}
instead of:
_[HOME]/administration/asset-manager/assetrelation/{new-id}_

* If the form has no parametrization, the returning page is:
_[HOME]/administration/asset-manager/_
instead of 
_[HOME]/administration/asset-manager/assetrelation_

Same thing happens when we are editing an existant record from the table.

So it seems the related module URL append is missing when returning from the new/detail form of the table.

**Comment by manuel-cid** [comment]
Your routes definition is wrowng.
You should configure the route with path `'assetrelation'` as a child route of the `'assetall'` route.
