### ISSUE TITLE
Filtering when using o-tree component

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#158]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>

[ x] Feature request

</code></pre>

## Current behavior
In the new component o-tree, there is a header where you can write to filter the entries in the tree. Right now nothing is changing when you write something

## Expected behavior
The component should have a parameter to indicate that you want to apply the filter for this specific type of nodes. This way, you can configure it for filtering in every tree level, or just in a specific one

**Comment by gonzalo-martinez-imt** [comment]
This bug will be fixed in the version 3.1.0 of ontimize-web-ngx-tree https://github.com/OntimizeWeb/ontimize-web-ngx-tree
