### ISSUE TITLE
show-root attribute in o-tree-node

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#160]
## I'm submitting a...
<pre><code>
[x ] Feature request
</code></pre>

## Current behavior
Currently, the component o-tree allows you to hide the root label of the tree, but they always appear in every o-tree-node

## Expected behavior
The o-tree-node can be used with the attribute "show-root", like o-tree

**Comment by gonzalo-martinez-imt** [comment]
o-tree-node now uses show-root input. But its only valid if the node has no siblings, otherwise its value its always true
