### ISSUE TITLE
Filter results when filter is null

### ISSUE THREAD

**Issue by ricardo-samaniego** [OntimizeWeb/ontimize-web-ngx#169]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
When filtering an o-table by the value of an o-combo, the result is the expected one as long as the o-combo has any value selected. When the o-combo has no selection, it appears that the filter is set to "attribute is null" instead of the expected "attribute is any value".

## Expected behavior
No filtering when no concrete filtering value is selected.

## Minimal reproduction of the problem with instructions

Example code:

```
<o-form fxLayout="row" label-header="Movements" header-actions="">
  <div fxLayout="row" layout-padding class="rounded-panel mat-elevation-z2">
      <o-combo fxFlex="100" attr="MOS_NAME" label="MOS_NAME" query-on-bind="yes" value-column="MOS_NAME" service="wcsmasters"
      entity="movementStatus" keys="MOS_ID" columns="MOS_NAME" visible-columns="MOS_NAME" class="margin-right-24"
      (onChange)="statusFilterEvent()"></o-combo>
  </div>

  <div fxLayout="row" style="height:15px"> </div>

  <div fxLayout="row" layout-padding class="rounded-panel mat-elevation-z2">
    <o-table #movementsTable service="movements" entity="movement" keys="MOV_ID" fxFlex parent-keys="MOS_NAME"
      columns="MOV_ID;MOS_NAME;MOV_PRIORITY;MOV_INSERT_DATE" visible-columns="MOV_ID;MOS_NAME;MOV_PRIORITY;MOV_INSERT_DATE"
      title="MOVEMENTS" query-on-init="true" query-rows="10" pageable="no" insert-button="yes">
    </o-table>
  </div>
</o-form>
```

## Environment

<pre><code>
Angular version: 4.3.6

</code></pre>

**Comment by gonzalo-martinez-imt** [comment]
This is the desired behaviour. In the future there will be available a filtering component/directive for making this kind of tasks automatically.

For doing this now you have to remove the table 'parent-keys' input and listen to the filtering components changes and then build your own filter and call the 'queryData' table method with that filter as first parameter
