### ISSUE TITLE
Context menu. Spanish translation

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#1717]
### What is the current behavior?
In spanish, context menu shows same option "Copiar celda" twice, when one of them should be "Copiar fila"

### Steps to reproduce
Right click in a table row. It can be checked on playgrounds

### Affected versions:
- `ontimize-web-ngx`: 8.X.X and 15.X.X

### Additional request
It would be helpful if bundles could be overwritten by app bundles, so this bug could be solved and maybe useful in other situations

**Comment by rodrigorodriguezgutierrez** [comment]
Ok, we just tried to overwrite it, and it works. Just in case somebody needs it: 

"TABLE_CONTEXT_MENU": {
    "COPY_ROW": "Copiar fila"
  }

**Comment by patricia-martinez-imatia** [comment]
Duplicate #1665
