### ISSUE TITLE
Use of o-table-cell-renderer-service 

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#175]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
The component o-table-cell-renderer-service is a bit ambiguous at the begining. It is needed to check the code to know how to configure it, because I could not find documentation. 

Let be LOC_ID a column in an o-table, from an entity A. Let be HWH_ID a column of another entity B (primary key HWH_ID). A.loc_id and B.hwh_id is the same. So, for every A.loc_id, I want it to go the the entity B to reach HWH_NAME.

      <o-table-column attr="LOC_ID" title="WAREHOUSE">
        <o-table-cell-renderer-service parent-keys="HWH_ID" service="warehouse" entity="hrWarehouse" columns="HWH_ID;HWH_NAME" value-column="HWH_NAME"></o-table-cell-renderer-service>
      </o-table-column>

If in the query, the filtering is not ok, more than one result will appear, so different LOC_ID will have the same HWH_NAME, because of o-table-cell-renderer-service.component.js, ln. 65:
                    self.responseMap[cellvalue] = resp.data[0][_this.valueColumn];

## Expected behavior
I do not know if that is the expected behaviour, but it would be useful to map all the values in one query (for example), and then the mapping would be done. Right know it is used a query for every new LOC_ID that would appear. 

Also, if I have LOC_ID= 4, what I would expect is the HWH_NAME where HWH_ID = 4.

</code></pre>

**Comment by manu-cr** [comment]
Hi @rodrigorodriguezgutierrez, the docs for the o-table-cell-renderer-service component are not ready yet, they will be available soon.

Regarding the unexpected values on the response, you are right and this will be fixed in the next release. For now, you can add the name of the column a parent-key, so the filter will include the column value.
