### ISSUE TITLE
cell edition mode in o-table when current value is null / empty string

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#185]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
When you want to edit a cell, its value can not be null. In this case, the edition mode it is not activated (the click or double-click does nothing)

## Expected behavior
Cells with null values should be settable

## Minimal reproduction of the problem with instructions
-Use an entity with allowed null values, and try to edit it. Then, click to edit
or
-Edit a not-null value. Delete the content of the cell. Then, click to edit

</code></pre>

**Comment by manu-cr** [comment]
We are aware of this issue and it is already solved in next release. Stay tuned!
