### ISSUE TITLE
Field <o-image> doesn't upload a image

### ISSUE THREAD

**Issue by pablo-martinez-imt** [OntimizeWeb/ontimize-web-ngx#186]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[X] Bug report  <em>Please search in other issues for a similar case before submitting</em>
</code></pre>

## Current behavior
When I try to upload a image, when it is processed by the JEE server, in the request, the value of the image is NullValue

## Expected behavior
When the resquest reaches the server, the image has its correct value

## Minimal reproduction of the problem with instructions
I have a form with the next component:

`<o-image id="CUSTOMER_PHOTO" attr="PHOTO" empty-image="assets/images/no-image.png"> 
</o-image>`

When I select an image, and click in save button, in the server the value of the image is NullValue

## What is the motivation / use case for changing the behavior?
Can upload a image

## Environment
<pre><code>
Angular version: 1.7.3
Browser: Check one of the following options with "x"
- [X] Chrome (desktop)  version  66.0.3359.181 64-bits
- [X] Firefox version version Developer Edition 61.0b8 64-bits

For Tooling issues:
- Node version:  v8.11.2
- Platform:  Windows
</code></pre>

**Comment by manu-cr** [comment]
Checking the type the `getValue()` method is returning and setting the proper value in the `sql-type` attribute should solve the proble.

**Comment by gonzalo-martinez-imt** [comment]
New BASE64 sql-type. Default in the o-image component
