### ISSUE TITLE
List-picker onChange event ignoring "clear action"

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#206]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
When you click "X", the event "onChange" is not fired

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
What **version** of ontimize-web-ngx are you using?

**Comment by rodrigorodriguezgutierrez** [comment]
The version we use is 3.0.0-rc.1

**Comment by patricia-martinez-imatia** [comment]
@rodrigorodriguezgutierrez  i can't reproduce the bug with the version 3.0.0-rc.1.

Below you will find an example 

<o-list-picker #listpicker attr="listpicker2" label="{{ 'INPUT.BUTTON.LISTPICKER' | oTranslate }}" [static-data]="getDataArray()"  [data]="getValue()" filter="yes" value-column="key" columns="key;value" visible-columns="value" required="true" read-only="false" (onChange)="onOChange($event)"></o-list-picker>

onOChange(e){
    console.log('launch the event');
  }

![event onchange](https://user-images.githubusercontent.com/32088627/45619307-18855300-ba79-11e8-8576-54dc4bea975d.gif)

**Comment by rodrigorodriguezgutierrez** [comment]
I cannot reproduce it again, and it works now. I guess I was doing something wrong that day. Thank you
