### ISSUE TITLE
Problems with the pagination of the grid

### ISSUE THREAD

**Issue by nona12** [OntimizeWeb/ontimize-web-ngx#220]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
* When in the grid you use the attribute "paginations-controls" as "yes" when you try to open the detail of an o-grid-item on the second page, always open the detail of an item on the first page
From what we have seen, the problem comes when registering the o-grid-items

</code></pre>

**Comment by manu-cr** [comment]
The fix for this will be available on the next release.
