### ISSUE TITLE
 Problems with the show-header-navigation of a form

### ISSUE THREAD

**Issue by nona12** [OntimizeWeb/ontimize-web-ngx#230]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
*Normally in the navigation bar of a form I have an arrow to go back, some navigation arrows to go to the next or previous record and some numbers that tell me how many records I have.

The problem is that at the moment I am in a detail form, I move to another page and return to the same detail of the form pressed in "back", the navigation bar of the form only has the arrow to go back , but the navigation arrows and the number of records disappears.*

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
Solving this problem is not trivial and at the moment we are not going to solve it,

**Comment by manuel-cid** [comment]
This feature is available since *ontmize-web-ngx@4.0.2*
