### ISSUE TITLE
 Problems with the progress spiner when I search with a Quick Filter in a Grid

### ISSUE THREAD

**Issue by nona12** [OntimizeWeb/ontimize-web-ngx#231]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
I have a grid with several rows of elements that force me to scroll if I want to see them all, and just at the top of the grid I have a Quick Filter that allows me to search among the elements of my grid.

When I use the Quick Filter, while the query is being made, the progress spiner appears below all of the grid, and that's a problem because if you don't scroll to see the spinner it seems that the filter is not doing anything.

## Expected behavior
The spinner should shade the page and appear on top of the elements, or appear at the top of the page so that it becomes easily visible

</code></pre>

**Comment by manu-cr** [comment]
This has been fixed in 7d08582 and will be available in the next release
