### ISSUE TITLE
Problem with the offset of a table

### ISSUE THREAD

**Issue by ctorreiro** [OntimizeWeb/ontimize-web-ngx#232]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
*I have a paged table inside a detail form. When the data in the table is consulted, the advanceQuery sends as an offset the number of records in the table of the previous record. Therefore, the response data is empty.*

## Environment

<pre><code>
Ontimize version: 3.1.2

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
As it is an ad-hoc filter of the components it is necessary to add to the queryData method another parameter, an object with the value **{offset: 0}**.
Example
yourcomponent.queryData(yourFilter,**{offset: 0}**);
