### ISSUE TITLE
Change labels and buttons text online

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#240]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
In our current version we are not able to modify input text label, after it was loaded. We are not sure with button text

## Expected behavior
We would like to be able to do it, because it is like a dynamic form where we don't have the label text before it is loaded. 

NOTE: Maybe it is possible in newer versions

## Environment

<pre><code>
OntimizeWeb version: 3.0.1
</code></pre>

**Comment by manuel-cid** [comment]
This works as expected from version 4 in advance
