### ISSUE TITLE
Problem with getDataValue of a OFormComponent

### ISSUE THREAD

**Issue by ctorreiro** [OntimizeWeb/ontimize-web-ngx#242]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
The function (onDataLoaded) of the form calls a method that checks if an o-text-input field has value.

When I try to check the value of the field I receive another oFormValue that inside has another value:
![image](https://user-images.githubusercontent.com/26895503/50687248-d7618080-1020-11e9-86b3-01990cfa32bd.png)

This is in case the field has no value. that is, in this case the correct value would be:
![image](https://user-images.githubusercontent.com/26895503/50687398-71292d80-1021-11e9-979e-157b164a72ed.png)

However when the field does have this it is returned correctly:

![image](https://user-images.githubusercontent.com/26895503/50687347-4048f880-1021-11e9-96b2-35818e3d4285.png)

## Expected behavior
*The getDataValue.value of an oFormComponent should always return the value regardless of whether it was undefined or not*

## Environment

<pre><code>
Angular version: 3.2.1

Browser: <em>Check one of the following options with "x"</em>
- [x] Chrome (desktop) version 70.0.3538.110
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: v8.12.0
- Platform:  Windows

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
You must use the method *getFieldValue* instead of *getDataValue*


```
getFieldValue
--
Return the current value of the control in the form
Parameters
attr: string
Returns
any
```


For more information you can consult the documentation of the o-form
https://ontimizeweb.github.io/docs/v3/components/form/
