### ISSUE TITLE
Define custom style for snackbar component

### ISSUE THREAD

**Issue by jaimepineiro** [OntimizeWeb/ontimize-web-ngx#260]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
We are using ontimize snackBarService to show snackbar, we want to change default style, but currently, object OSnackBarConfig does not allow to set panelClass as angular material snackbar component do ([https://v6.material.angular.io/components/snack-bar/api#MatSnackBarConfig]).
Otherwise, we need to set also icon style. Then it would be great to have another property like "iconClass" to set its style.

## Expected behavior
OSnackBarConfig having two more properties, "panelClass" and "iconClass" to set custom styles for snackbar panel and icon, respectibly.

**Comment by manuel-cid** [comment]
We are adding the `cssClass` attribute to the `OSnackBarConfig` that will set the angular `panelClass`. This attribute will be available in the next release.
Regarding the `iconClass` attribute, we are not implementing it due to it is already possible to customize the icon.
