### ISSUE TITLE
o-table: o-table-insertable-row doesn't work

### ISSUE THREAD

**Issue by RodrigoBreton** [OntimizeWeb/ontimize-web-ngx#261]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
When you try to put in a o-table an o-table-insertable-row nothing happens and nothing is inserted.

## Expected behavior
The o-table-insertable-row should let you insert a new row in the table.

## Minimal reproduction of the problem with instructions
This is the playground link for the o-insertable-row: https://try.imatia.com/ontimizeweb/playground/main/table/insertablerow, here you can see the error, the table doesn't let insert anything in the example table.

This is the playground capture

![CapturaBug](https://user-images.githubusercontent.com/49713448/56278715-077feb80-6107-11e9-8b7d-debdca21d9c9.PNG)

## What is the motivation / use case for changing the behavior?
I would like to insert rows in the table.

## Environment

<pre><code>
Angular version: 1.7.3

- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 66.0.3
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 10.15.3 
- Platform:  <em>Windows</em>

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
It will be available in the next release
