### ISSUE TITLE
QuickFilter for pageable table is not working if type is not string

### ISSUE THREAD

**Issue by jaimepineiro** [OntimizeWeb/ontimize-web-ngx#263]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior

We have a pageable table with some integer columns. 
When user types in quickFilter. It's not filtering by this column.
We have noted that this parameter is not beeing added in filter_expression sent to the server.
We tested also with column types: real and currency.
## Expected behavior
Filter for columns that are not string must be in filter_expression sent to the server.

## What is the motivation / use case for changing the behavior?
User needs to filter by numeric columns

## Environment

<pre><code>
Ontimize web: 4.0.2
Angular version: 6.1.10

Browser: <em>Check one of the following options with "x"</em>
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by manuel-cid** [comment]
We are developing some improvements on table filtering so filtering **numeric** columns will work on release 4.0.4.
