### ISSUE TITLE
Table column filter can only filter for current page in pageable tables

### ISSUE THREAD

**Issue by jaime-pineiro-imatia** [OntimizeWeb/ontimize-web-ngx#264]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
When user opens column filter in pageable table. Only values for that page are shown. Even if he types in filter, the list is filtered but only by data for this page. Otherwise, when some value is picked, table values are beeing filtered in the server, then, page content is updated.

## Expected behavior
When user type something in column filter filter. Filter list must match any value (query server side), not only values for current page.

## Minimal reproduction of the problem with instructions

In https://try.imatia.com/ontimizeweb/quickstart/main/customers, try to use column filter to match a value that is in second page, beeing in first page

## What is the motivation / use case for changing the behavior?
We think column filter must be coherent, if query is done server side to fill the table. Column filter filter must also query server side to fill the list.

## Environment

<pre><code>
Ontimize web version: 4.0.2
Angular version: 6.1.10

Browser: <em>Check one of the following options with "x"</em>
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by pacogomezimatia** [comment]
This issue is solved in last version 4.1.2, you can check this working [here](https://try.imatia.com/ontimizeweb/quickstart/main/customers)
