### ISSUE TITLE
 Problems to have more than two environments

### ISSUE THREAD

**Issue by nona12** [OntimizeWeb/ontimize-web-ngx#266]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
*I need to have more than two environments.
For this, what I have done is create two new environments files with two different apiEndpoints and in the scripts of my package.json add the enviroment attribute with the name of the file in the environmnet of test, but this is not working for me.*

    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "production": "ng build --aot=false --target -prod",
        "test-aot": "ontimize-web-ngx production-aot --project-name employees-portal --href /employees-portal/ environment environment.test",
        "production-aot": "ontimize-web-ngx production-aot --project-name employees-portal --href /employees-portal/"
    },

## Expected behavior
*What should happen is that the dist of the development environment is created in a normal way as it has worked so far, but when I want to generate the dist of the test environment, through the environment attribute that I have added, I take the environment file .test.ts*

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
hi @nona12,

You have to change :

1.  Change "test-aot" script
```
"scripts": {
    ...
    "test-aot": "ontimize-web-ngx production-aot --project-name employees-portal --href /employees-portal/ --configuration=test,
    ...
},
```

2. Add new enviroment  in  configurations in angular.json file

![issue_266](https://user-images.githubusercontent.com/32088627/66481346-07065300-eaa1-11e9-9db9-28eca9de061e.PNG)
