### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by GRT1979** [OntimizeWeb/ontimize-web-ngx#268]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
* src/app/main/customers/edit/customers-edit.component.html doesn't exist.*

## Expected behavior
*Modify src/app/main/customers/edit/customers-edit.component.html.*

## Minimal reproduction of the problem with instructions
<em>Is not possible to make these 2 examples: "Listen to an event" && "Open a form" following this doc --> [Link](https://ontimizeweb.github.io/docs/make-changes/)</em>

## What is the motivation / use case for changing the behavior?
*Report outdated information.*

## Environment

<pre><code>
Angular version: X.Y.Z

Browser: <em>Check one of the following options with "x"</em>
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: XX  <em>run `node --version`</em>
- Platform:  <em>Mac, Linux, Windows</em>

Others:
<em>I'm working with ontimize-web-ngx-quickstart (4.0.0-rc.0) </em>

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
The documentation was updated. Thank you for reporting it.
