### ISSUE TITLE
Doc navigation

### ISSUE THREAD

**Issue by GRT1979** [OntimizeWeb/ontimize-web-ngx#269]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
*Following the link  from Doc "Guide --> App Configuration" to Next article is wrong (goes to Remote configuration).*

## Expected behavior
*Following the link  from Doc "Guide --> App Configuration" to Next article should goes to "Application modules".*

## Minimal reproduction of the problem with instructions
<em>It's possible to reproduce this error from this [link](https://ontimizeweb.github.io/docs/guide/appconfig/)</em>

## What is the motivation / use case for changing the behavior?
*Report a doc navigation bug.*

## Environment

<pre><code>
Angular version: X.Y.Z

Browser: <em>Check one of the following options with "x"</em>
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: XX  <em>run `node --version`</em>
- Platform:  <em>Mac, Linux, Windows</em>

Others:
<em>Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ...</em>

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
This bug is solved, thank you for reporting it.
