### ISSUE TITLE
Outdated information at Doc

### ISSUE THREAD

**Issue by GRT1979** [OntimizeWeb/ontimize-web-ngx#271]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
*Instruction proposed at doc doesn't work.*

## Expected behavior
*It should works correctly. I propose a solution*

## Minimal reproduction of the problem with instructions
<em>In the following doc --> [Link](https://ontimizeweb.github.io/docs/guide/service/) there are instructions like: 

`const dataObservable = new Observable(observer => _innerObserver = observer).share();` 

that aren't recognize with RxJs 6.3.3 version. Instead of that instruction should be:  

`const dataObservable = new Observable(observer => _innerObserver = observer).pipe(share());`

To see more details: [Link](https://stackoverflow.com/questions/50885262/replacing-the-share-function-for-in-rxjs6)</em>

## What is the motivation / use case for changing the behavior?
*Report outdated information.*

## Environment

<pre><code>

Angular CLI: 6.2.6
Node: 10.15.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.9
@angular-devkit/build-angular      0.8.9
@angular-devkit/build-optimizer    0.8.9
@angular-devkit/build-webpack      0.8.9
@angular-devkit/core               0.8.9
@angular-devkit/schematics         0.8.6
@angular/cdk                       6.4.7
@angular/cli                       6.2.6
@angular/flex-layout               6.0.0-beta.18
@angular/material                  6.4.7
@angular/material-moment-adapter   6.4.7
@ngtools/webpack                   6.2.9
@schematics/angular                0.8.6
@schematics/update                 0.8.6
rxjs                               6.3.3
typescript                         2.9.2
webpack                            4.18.0

Others:
<em>I'm working with ontimize-web-ngx-quickstart (4.0.0-rc.0) </em>

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
The documentation was updated. Thank you for reporting it.
