### ISSUE TITLE
Horizontal scroll on a o-table

### ISSUE THREAD

**Issue by ctorreiro** [OntimizeWeb/ontimize-web-ngx#273]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
*I have a table with `horizontal-scroll = "no"` when modifying the default configuration appears the horizontal scroll. When returning to the default configuration the scroll does not disappear.*

## Expected behavior
*When you have a table with `horizontal-scroll = "no"` it should not appear when modifying the default configuration. If it appears, it should disappear when you return to the default configuration*

## What is the motivation / use case for changing the behavior?
*To avoid the appearance of horizontal scroll*

## Environment

<pre><code>
ontimize-web-ngx version: 4.0.5

Browser: <em>Check one of the following options with "x"</em>
- [x] Chrome (desktop) version 74.0.3729.169
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: v8.12.0
- Platform:   Windows

</code></pre>

**Comment by pacogomezimatia** [comment]
#409
