### ISSUE TITLE
Sort o-table-column-calculated

### ISSUE THREAD

**Issue by ctorreiro** [OntimizeWeb/ontimize-web-ngx#277]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
*When I try to sort a calculated column the values ​​are not sorted correctly*

![image](https://user-images.githubusercontent.com/26895503/61111298-904dbf80-a489-11e9-990d-521910d65783.png)

## Expected behavior
*It should be possible to order the column even if it was calculated*

## Minimal reproduction of the problem with instructions
The html of the table is:

`
<o-table #allHours entity="EMobLAEmpleadosPresenceControlHours" attr="allHours" keys="presence_control_hours_id"
         columns="employee_id;init_date;end_date;minutes;month" visible-columns="init_date;end_date;hours"
         refresh-button="yes" delete-button="yes" insert-button="no" pageable="yes" selection-mode="single"
         detail-mode="none" edition-mode="click" service-type="FilterByEmployee" query-method="queryFiltered"
         quick-filter="yes" (onDataLoaded)="managerButtons()" (onRowDeleted)="reloadData()" query-rows="7">
         <o-table-button (onClick)="insertDateTime()" label="{{'insert' | oTranslate }}" icon="add"></o-table-button>
         <o-table-button *ngIf="startActivated" (onClick)="startTiming()" label="{{'play' | oTranslate }}"
            icon="play_arrow"></o-table-button>
         <o-table-button *ngIf="stopActivated" (onClick)="stopTiming()" label="{{'stop' | oTranslate }}" icon="stop">
         </o-table-button>
         <o-table-column title="{{ 'init_date' | oTranslate }}" attr="init_date" type="time" editable="true"
            (editionCommitted)="editionCommitted()">
            <o-table-cell-renderer-date format="DD-MM-YYYY - HH:mm"></o-table-cell-renderer-date>
         </o-table-column>
         <o-table-column title="{{ 'end_date' | oTranslate }}" attr="end_date" type="time" editable="true"
            (editionCommitted)="editionCommitted()">
            <o-table-cell-renderer-date format="DD-MM-YYYY - HH:mm"></o-table-cell-renderer-date>
         </o-table-column>
         <o-table-column-calculated title="{{ 'hours' | oTranslate }}" attr="hours" operation="(minutes/60)"
            decimal-separator=",">
            <o-table-cell-renderer-real decimal-digits="2" decimal-separator="," grouping="yes" thousand-separator=".">
            </o-table-cell-renderer-real>
         </o-table-column-calculated>
      </o-table>
`

## Environment

<pre><code>
ontimize-web-ngx version: 4.0.6-5-SNAPSHOT

Browser: 
- [x] Chrome (desktop) version 75.0.3770.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: v8.12.0
- Platform:  Windows

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
Hi Cristina, 

You can add the complete code of the table.
It is possible that there is another ordered column that has higher priority in the ordering, the table allows the multiple ordering of columns.

**Comment by patricia-martinez-imatia** [comment]
Closed due to inactivity.
