### ISSUE TITLE
Performing "npm i" with Node 12 fails

### ISSUE THREAD

**Issue by jLagosCarrera** [OntimizeWeb/ontimize-web-ngx#279]
## I'm submitting a...
<pre><code>
[ x] Regression (a behaviour that used to work and stopped working in a new release)
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Trying to use "npm install" with Node version 12 fails because the version of node-sass used on the framework is incompatible with the Node version.

## Expected behaviour
Perform installation of all the dependencies without failing.

## Minimal reproduction of the problem with instructions
Install Node version 12, download latest release or master branch and perform "npm install"

## What is the motivation / use case for changing the behaviour?
The solution to this problem lays on upgrading node-sass version to the latest (4.12.0), which supports Node 12 version. Further information on the following link: https://www.npmjs.com/package/node-sass.

## Environment

<pre><code>
ontimize-web-ngx version: 4.0.6

For Tooling issues:
- Node version: 12
- Platform: Windows
</code></pre>

**Comment by patricia-martinez-imatia** [comment]
Thank you for your collaboration
