### ISSUE TITLE
Option to minimize menu bar to buttom in mobile mode

### ISSUE THREAD

**Issue by FLCostas** [OntimizeWeb/ontimize-web-ngx#281]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
If we configure the `o-app-layout` with the `mobile` mode it shows in the top of the screen a header with the user and the idiom of de app.

## Expected behavior
It would be great if only the menu drop-down button could be left in floating mode, to have the entire screen available for the app.

## What is the motivation / use case for changing the behavior?
By this way we can use the full screen, and in mobile devices this is very usefull because the screen size.

## Environment

<pre><code>
ontimize-web-ngx version: 4.0.6

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
Hi @FLCostas ,
 For this case, the easiest would be:
1. Hide the header in  o-app-layout with 'show-header="no"'
2. Add your button in the template that is the component  o-app-layout

For example

**main.component.html**

```
<o-app-layout #appLayout class="my-app-layout" mode="mobile" use-flag-icons="true" opened-sidenav-image="./assets/images/logo_extenso.png"  closed-sidenav-image="./assets/images/logo.png">

  <mat-icon class="my-sidenav-toggle" (click)="toogleSidenav($event)" svgIcon="ontimize:menu">/mat-icon>

  <router-outlet></router-outlet>

</o-app-layout>
```

`

**main.component.ts**
```
 toogleSidenav() {
    this.appLayout.appSidenav.toggleSidenav();
  }

```

**main.component.css**
```
o-app-layout.my-app-layout {
  .my-sidenav-toggle{
    position: absolute;
    top:0;
  }
}
```
