### ISSUE TITLE
insert-button in top of list

### ISSUE THREAD

**Issue by FLCostas** [OntimizeWeb/ontimize-web-ngx#282]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
When we activate the `insert-button="yes"` in a `o-list`, then the insert button is placed at the bottom of the list. If the list is greater than the form, it isn't visible, we must scroll the list to see it.

## Expected behavior
Would be nice we can configure if we want the button at the top or the bottom of the list.

## What is the motivation / use case for changing the behavior?
If we can set the insert button at the top of the list, it would always be visible, regardless of the size of the list.

## Environment

<pre><code>
ontimize-web-ngx version: 4.0.6

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
One question,  Do you prefer the insert button to be on the toolbar instead of floating on the top?

**Comment by FLCostas** [comment]
Yes, it's a good position too.
Thanks.

**Comment by patricia-martinez-imatia** [comment]
@FLCostas can add the insert button:
1. In the toolbar, so that it is not floating, with the option insert-button-floatable = "no"
2. And if it is floating insert-button-position = "top"
   insert-button-floatable = "yes"
