### ISSUE TITLE
oTable: New columns hidden by preferences

### ISSUE THREAD

**Issue by davidrodriguezlosada** [OntimizeWeb/ontimize-web-ngx#284]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
I have an application already deployed in a production enviroment. When I add new columns to my tables they are beign hide by default.

## Expected behavior
When I add a new column to a table I expect it to be shown to the users.

## Minimal reproduction of the problem with instructions
Add new columns to a table where you already have some preferences saved.

## Environment

<pre><code>
ontimize-web-ngx version: 4.0.6-5-SNAPSHOT

Browser: <em>Check one of the following options with "x"</em>
- [x ] Chrome (desktop) version 76
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: XX  <em>run `node --version`</em>
- Platform:  <em>Mac, Linux, Windows</em>

Others:
<em>Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ...</em>

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
This bug will be fixed in version 4.0.7
