### ISSUE TITLE
Combo in empty request result

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#291]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
If the Http request returns the field "data" as empty object **{}**, instead of array, the component fails, and other components in the form too, due this bug. 

Here is the problem (we solved it in local)
OComboComponent.prototype.setDataArray = function (data) {
          _super.prototype.setDataArray.call(this, data);
          this.filteredDataArray = data;
    };

OComboComponent.prototype.setDataArray = function (data) {
        _super.prototype.setDataArray.call(this, data);
        if (Util.isObject(data) && Object.keys(data).length == 0)
            this.filteredDataArray = [];
        else
            this.filteredDataArray = data;
    };

filteredDataArray is an empty object, instead of an empty array

## Environment

<pre><code>
ontimize-web-ngx version: 4.0.7-13-SNAPSHOT

Browser: <em>Check one of the following options with "x"</em>
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by patricia-martinez-imatia** [comment]
hi @rodrigorodriguezgutierrez ,

This issue is not a bug,  the server response interfaz defines that return an array not an object, in your case a empty array as you can see in the documentation https://ontimizeweb.github.io/docs/guide/service/#server-response-interface

**Comment by rodrigorodriguezgutierrez** [comment]
Yes, but the thing is that Ontimize Server is the one sending that format, so I can not change it. Also, this worked for previous versions of ontimize-web-ngx, because we did not change the version of Ontimize server.

As I see, the variable this.dataArray is correctly set to [] when it detects an empty object. However, this.filteredDataArray is not set to [] in the same situation
