### ISSUE TITLE
Problems going back from form by using back arrow 

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#292]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
Let us say that we have three forms connected: A -> B -> C. If we are in C, and go back, it goes to B, and if we try to go back again, it goes to C again.

## Expected behavior
The order must be respected when going back.

<pre><code>
ontimize-web-ngx version: 4.0.8-1-SNAPSHOT

Browser: <em>Check one of the following options with "x"</em>
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: XX  <em>run `node --version`</em>
- Platform:  <em>Mac, Linux, Windows</em>

Others:
<em>Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ...</em>

</code></pre>

**Comment by manuel-cid** [comment]
Already solved
