### ISSUE TITLE
Problem getting value of o-hour-component

### ISSUE THREAD

**Issue by davdes15** [OntimizeWeb/ontimize-web-ngx#300]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
The o-hour-component returns String when the hours are typed in instead of using the clock widget

## Expected behavior
The o-hour-component should return the time in miliseconds regardless of the way they're introduced

## Minimal reproduction of the problem with instructions
Add an o-hour-component to an angular app, use the getValue method for said component, the value received is a String when the time is typed in and the time in miliseconds when it's introduced using the clock widget

## Environment

<pre><code>
ontimize-web-ngx version: 4.1.0

Browser: <em>Check one of the following options with "x"</em>
- [x] Chrome (desktop) version  79.0.3945.130
- [x] Chrome (Android) version  79.0.3945.116
- [ ] Chrome (iOS) version XX
- [x] Firefox version 70.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 10.17.0 
- Platform: Windows

**Comment by pacogomezimatia** [comment]
Hello @davdes15, could you paste the code of the o-hour-input added to your application?

**Comment by pacogomezimatia** [comment]
#312
