### ISSUE TITLE
Can't edit 'o table cell editor text' after table refresh

### ISSUE THREAD

**Issue by jorge-cabaleiro-imatia** [OntimizeWeb/ontimize-web-ngx#301]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

In a table with a column rendered with an 'o table cell editor text', with just one row, the field can't be edited after using the refresh button of the table.

To be able to edit the field again, I have to move the focus outside the row, pick the row focus in other column, and then the field can be edited again.

## Expected behavior

To be able to edit the 'o table cell editor text' after refreshing the table.

## Minimal reproduction of the problem with instructions

With this table with just one row:

```html
<o-table #documentsTable keys="ID" service="files" entity="file"
  parent-keys="CANDIDATE:ID" columns="ID;FILENAME;DESCRIPTION"
  visible-columns="FILENAME;DESCRIPTION;DOWNLOAD" insert-button="false"
  detail-mode="none" edition-mode="click" selection-mode="simple"
  query-on-init="yes" class="rounded-panel" fixed-header="yes">

  <o-table-button #uploadFileButton attr="UPLOAD" label="UPLOAD" icon="cloud_upload">
  </o-table-button>
  
  <o-table-column attr="DESCRIPTION" title="DESCRIPTION" type="string" editable="yes">
    <o-table-cell-editor-text></o-table-cell-editor-text>
  </o-table-column>
  
  <o-table-column attr="DOWNLOAD" title="DOWNLOAD" width="20px">
    <o-table-cell-renderer-action (onClick)="downloadFile($event)" icon="cloud_download">
    </o-table-cell-renderer-action>
  </o-table-column>

</o-table>
```

1. Edit the description column.
2. Click on the refresh button.
3. Can't edit the description column.

## What is the motivation / use case for changing the behavior?

The field must be editable after using the refresh button.

## Environment

<pre><code>
ontimize-web-ngx version: 4.1.0

Browser: <em>Check one of the following options with "x"</em>
- [x] Chrome (desktop) version 79.0.3945.130
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 73.0b12
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 44.18362.1.0

For Tooling issues:
- Node version: v8.12.0
- Platform:  Windows

</code></pre>

**Comment by pacogomezimatia** [comment]
#311
