### ISSUE TITLE
Property to show/hide o-table configuration menu option

### ISSUE THREAD

**Issue by jaimepineiro** [OntimizeWeb/ontimize-web-ngx#306]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
*Describe how the issue manifests.*

## Expected behavior
We need a property to hide o-table configuration menu option
![image](https://user-images.githubusercontent.com/45460679/74514039-1e03f880-4f0c-11ea-94d7-42d237dbdcda.png)

## Minimal reproduction of the problem with instructions
<em>For bug reports provide, if you can, a minimal set of steps to reproduce it</em>
<em>In case you are reporting a styling issue or something similar it would be great if you give us a screenshot describing your problem</em>

## What is the motivation / use case for changing the behavior?
Our client ask us to hide this section

## Environment

<pre><code>
ontimize-web-ngx version: 4.1.1

Browser: <em>Check one of the following options with "x"</em>
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: XX  <em>run `node --version`</em>
- Platform:  <em>Mac, Linux, Windows</em>

Others:
<em>Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ...</em>

</code></pre>

**Comment by pacogomezimatia** [comment]
#308
