### ISSUE TITLE
Form :: label header not shown in edit mode

### ISSUE THREAD

**Issue by denislamela** [OntimizeWeb/ontimize-web-ngx#31]
When you go to the edit page of a detail form it doesn't show the label header, only the buttons to edit or cancel.

Version 1.0.2

**Comment by daniel-grana** [comment]
Right now it is the desired behavior. Maybe a parameter can be added to allow display label header on edition and/or insertion

**Comment by patricia-martinez-imatia** [comment]
This issue is solved with the attribute `label-header` in o-form component.
You can consult the documentation in [https://ontimizeweb.github.io/docs/components/form/](https://ontimizeweb.github.io/docs/components/form/)
