### ISSUE TITLE
Tables export error

### ISSUE THREAD

**Issue by rodrigorodriguezgutierrez** [OntimizeWeb/ontimize-web-ngx#325]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
"Export" button of table is not working, at least in some of 4.1.X versions. It works in previous versions. 
The problem is that the request URL is wrong.

</code></pre>

**Comment by manuel-cid** [comment]
The exportation has changed in release [4.1.0](https://github.com/OntimizeWeb/ontimize-web-ngx/releases/tag/4.1.0)
Check the [breaking changes](https://github.com/OntimizeWeb/ontimize-web-ngx/blob/master/CHANGELOG.md#breaking-changes) for that release
