### ISSUE TITLE
Ontimize services extension

### ISSUE THREAD

**Issue by jokromero** [OntimizeWeb/ontimize-web-ngx#326]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
The only Ontimize-web service I can extend is OntimizeEEService throught the "serviceType" property in the app.config.ts file.

## Expected behavior
It'll be great if others service like the OntimizeExportService or FileUploadService could be extended in the same way.

## What is the motivation / use case for changing the behavior?
I need add custom headers to all request my app make to the server.

## Environment
<pre><code>
ontimize-web-ngx version: 4.1.0

</code></pre>

**Comment by jokromero** [comment]
Hello,

The purpose of the request was to be able to extend any ontimize service. For example, now I have a problem with o-translate-service and I can't extend it to fix it.
It would be nice if all these kinds of services could be extended.

Thanks.

**Comment by manuel-cid** [comment]
We are currently looking for a better solution to this topic
