### ISSUE TITLE
Checkbox does not admit string values

### ISSUE THREAD

**Issue by sergiootero5** [OntimizeWeb/ontimize-web-ngx#328]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
I try to use a <o-checkbox> in a new component like this:
`<o-checkbox #maxFreeCons attr="TEN_USE_TTS" sql-type="STRING" boolean-type="string" false-value="N" true-value="Y"></o-checkbox>`

The data sended should be "Y" and "N" but in the request data it's sending booleans true and false. 
The correct value to the data base recognized it should be a string "Y" "N"

## Environment

<pre><code>
ontimize-web-ngx version: 4.1.2

</code></pre>

**Comment by pacogomezimatia** [comment]
Hello @sergiootero5 ,

I have tried to get the same error but it is working fine. Maybe you can post the typescript code to check how you are accessing to this value.

**Comment by pacogomezimatia** [comment]
#329

**Comment by iibraiscabaleiro** [comment]
We're having the same problem in the version 8.14.5 but only when the form is in "new" mode in the detail one is working as expected.
