### ISSUE TITLE
stay-in-record-after-insert action fails after new module routing inside o-form-manager

### ISSUE THREAD

**Issue by FLCostas** [OntimizeWeb/ontimize-web-ngx#389]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
In a form with 'stay-in-record-after-insert="yes" inside a o-form-manager, no routing to edit form, stay in new form.
If the 'o-form-manager' is removed, it works ok.

## Expected behavior
Work the same way with 'o-form-manager', opening the edit form after insert.

## Environment

<pre><code>
ontimize-web-ngx version: 4.1.2

Browser: <em>Check one of the following options with "x"</em>
- [x] Chrome (desktop) version  83.0.4103.116
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 78.0.1
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by pacogomezimatia** [comment]
#393
