### ISSUE TITLE
Event onChange doesn't work for o-combo element with multiple="yes"

### ISSUE THREAD

**Issue by fran-ca** [OntimizeWeb/ontimize-web-ngx#430]
On version 4.1.2 the event onChange is not triggered when the elements are selected on a o-combo with "multiple" atribute set on yes.

**Comment by patricia-martinez-imatia** [comment]
hi @fran-ca,

You can provide more data, in our tests the event **onChange** is triggered  correctly when a value is selected in a multiple combo.
