### ISSUE TITLE
o-checkbox no selected, no value

### ISSUE THREAD

**Issue by Fonsi20** [OntimizeWeb/ontimize-web-ngx#442]
Error in ^4.1.0 and 4.2.0-SNAPSHOT-4

I have a o-checkbox in a dialog and with the false-value and true-value defined in the html, but when i try to obtain the **this.myCheckBox.getValue(), the value is Undefined** because doesn't exist the "value" in the checkbox, but if i check the checkbox(and now it's True)  **this.myCheckBox.getValue() gives me "True" correctly**.

my own solution for this was:
```
ngOnAferViewInit() {
    this.oForm.setFieldValue("is_personal_days", false);
  }
```

**Comment by pacogomezimatia** [comment]
#471
