### ISSUE TITLE
Table with expandable rows

### ISSUE THREAD

**Issue by Fonsi20** [OntimizeWeb/ontimize-web-ngx#443]
![image](https://user-images.githubusercontent.com/12035327/94407976-77a3f500-0174-11eb-9912-beb51ead0bc1.png)
(Example [expandable rows angular material](https://material.angular.io/components/table/examples))
- We need to be able to decide between multiple or individual display of rows, display all the rows that we want or just one at a time, if we display another that closes the previous one.
- We want to be able to decide between clicking anywhere on the row to expand it or a button that appears to expand it.
- In the case of being able to click anywhere on the row to expand it, be able to block columns so that it does not expand when clicking on them, for example if a column is a button or a checkbox.
- That the expandable content can be from tables, images, text, etc ...
- Make the query to get the expandable information only when the row is displayed.
- That the display of rows or the click trigger events that we can capture.
- To be able to select rows and that later we can obtain the information of the selected rows.

**Comment by patricia-martinez-imatia** [comment]
#447
