### ISSUE TITLE
o-combo: Add attribute to enable/disable edit

### ISSUE THREAD

**Issue by dr-mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ngx#49]
New attribute for o-combo, to control manual entry: 
Exp: editable = yes/no (yes: can write manualy a value / no: disable keyboard entry, only selection is enabled)

**Comment by pacogomezimatia** [comment]
This is solved with the attribute _searchable_. You can see the complete documentation [here] (https://ontimizeweb.github.io/docs/components/input/combo/)
