### ISSUE TITLE
o-table-column-aggregate doesn't show the values obtained calling the function-aggregate

### ISSUE THREAD

**Issue by marlaior** [OntimizeWeb/ontimize-web-ngx#498]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior

I have a o-table-column with type="real". This column shows a numeric value but it can also  add an icon when the record has a comment. In addition to this, I add an o-table-column-aggregate with an aggregate-function but it doesn't show the column total. It displays the title of the aggregated column but doesn't display the values. I tried to change the "real" type to "text" type but it only shows the title too.

## Expected behavior
It should show the sum of the values in the aggregated column keeping the current rendering with the icon in the original column

## Minimal reproduction of the problem with instructions

The html for the o-column:
`<o-table-column attr="tue" title="{{ 'TUE' | oTranslate }}" type="real" (editionStarted)="openTimeTrackingDialog($event, 'tue')">
      <app-comment-tuesday></app-comment-tuesday>
    </o-table-column>`

The html of that "app-comment-tuesday" (it displays the value in the column):
`<ng-template #templateref let-cellvalue="cellvalue" let-rowvalue="rowvalue" type="real" title-align="end"
  content-align="end" orderable="no" editable="yes" thousand-separator="," decimal-separator="." min-decimal-digits="0"
  max-decimal-digits="2">
  <span *ngIf="rowvalue && rowvalue['tue_comment']" fxLayoutAlign="center" type="real">
    {{rowvalue['tue']}}   <mat-icon style="color:green; font-size: 16px; padding-top: 1px;">feedback</mat-icon>
  </span>
  <span *ngIf="rowvalue && !rowvalue['tue_comment']" style="color:black;" fxLayoutAlign="center">
    {{rowvalue['tue']}}
  </span>
</ng-template>`

The html for tht aggregate column:
`<o-table-column-aggregate attr="tue" title="{{'TOTAL' | oTranslate}}  (h)" [function-aggregate]="prueba">`

The typescript code called by the function-aggregate:
`public prueba(data: [any]):number{
    return 7;
  }`

This should show a 7 in the added column but doesn't:

![Selection_table](https://user-images.githubusercontent.com/21356109/106592489-daa4fe80-654f-11eb-8003-4464a128dd62.png)

## What is the motivation / use case for changing the behavior?
I need to use the function-aggregate 'cause if without it, the aggregate column overwrites the o-column code and doesn't display the comment icon:
![Selection_table2](https://user-images.githubusercontent.com/21356109/106594063-e0034880-6551-11eb-926d-a411f95d1763.png)

## Environment

<pre><code>
ontimize-web-ngx version: 8.0.0

Browser: <em>Check one of the following options with "x"</em>
- [x] Chrome (desktop) version 87.0.4280.88

For Tooling issues:
- Node version: 12.10.0
- Platform:  Ubuntu 20.04

**Comment by pacogomezimatia** [comment]
Hello @marlaior,

We have checked this behaviour and it´s working fine. 
To achieve this you must follow the steps described in the section of _Custom Renderers_ for the _Table Component_ [here](https://ontimizeweb.github.io/docs/components/table/overview).

Our custom renderer template:
`<ng-template #templateref let-cellvalue="cellvalue" let-rowvalue="rowvalue">
  {{ getCellData(cellvalue, rowvalue) }}<mat-icon style="color:green; font-size: 16px; padding-top: 1px;">feedback</mat-icon>
</ng-template>`

The typescript:
`getCellData(cellvalue: any, rowvalue: Object) {
    let value: any;
    value = rowvalue ? rowvalue['tue_comment'] : cellvalue;
    return value;
  }`

This is the HTML:
`<o-table-column attr="tue_comment" title="tue_comment" type="integer">
        <custom-render></custom-render>
      </o-table-column>
      <o-table-column-aggregate attr="tue_comment" title="(Min)" [function-aggregate]="prueba"></o-table-column-aggregate>`

The problem in your code is that your are not showing the variable for the aggregate column cellvalue.

Hope it helps!
