### ISSUE TITLE
o-table-columns-filter-column should accept format like o-table-column

### ISSUE THREAD

**Issue by etcid** [OntimizeWeb/ontimize-web-ngx#508]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
o-table-column allow type and format (example MM-YYYY)
o-table-columns-filter-column dont allow pass any format

## Expected behavior
o-table-columns-filter-column should accept format like o-table-column

## Environment

<pre><code>
ontimize-web-ngx version: 8.1.1
</code></pre>

**Comment by pacogomezimatia** [comment]
#516
