### ISSUE TITLE
o-combo and o-list-picker should accept format like o-table-column 

### ISSUE THREAD

**Issue by etcid** [OntimizeWeb/ontimize-web-ngx#529]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
o-combo and o-list-picker dont accept format like o-table-column and it is a problem for date data for example

## Expected behavior
o-combo and o-list-picker should accept format like o-table-column 

## What is the motivation / use case for changing the behavior?
I think it is useful in the cases of dates especially, to change timestamp to other formats values

## Environment

<pre><code>
ontimize-web-ngx version: 8.1.1
</code></pre>

**Comment by pacogomezimatia** [comment]
#540
