### ISSUE TITLE
Slide-toggle .getValue() always return false

### ISSUE THREAD

**Issue by FranRuizEsc** [OntimizeWeb/ontimize-web-ngx#533]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
*o-slide-toogle, I can´t acces to getValue() always gives me back false *

## Expected behavior
*return getValue() true or false based on switch status .*

## Minimal reproduction of the problem with instructions
<em>For bug reports provide, if you can, a minimal set of steps to reproduce it</em>
<em>In case you are reporting a styling issue or something similar it would be great if you give us a screenshot describing your problem</em>
![image](https://user-images.githubusercontent.com/60076220/109290513-f9817280-7827-11eb-8b75-c2d7b90e6b11.png)

## What is the motivation / use case for changing the behavior?
*componet slideToogle.getValue() returun always false*

## Environment

<pre><code>
ontimize-web-ngx version: 8.1.1

Browser: <em>Check one of the following options with "x"</em>
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 12.16.2  <em>run `node --version`</em>
- Platform: Windows <em> Windows</em>

Others:
<em>Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ...</em>

</code></pre>

**Comment by pacogomezimatia** [comment]
#535
