### ISSUE TITLE
Tables - Expandable multiple

### ISSUE THREAD

**Issue by Fonsi20** [OntimizeWeb/ontimize-web-ngx#545]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
We dosen't find the option for can open multiples lines in a table expandable. I share you a example that what we need.
[Example multiple expandable](https://stackblitz.com/edit/angular-kkt6ny?file=app%2Ftable-expandable-rows-example.ts)
![asdasdasdasdsdasdadad](https://user-images.githubusercontent.com/12035327/110954833-3df13000-8349-11eb-89d9-538003e55624.PNG)

## Environment
<pre><code>
ontimize-web-ngx version: 4.2.1

Browser: <em>Check one of the following options with "x"</em>
- [ X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by Fonsi20** [comment]
Can you put this option in the 4.X.X version?

**Comment by patricia-martinez-imatia** [comment]
hi @Fonsi20 , this feature will also be included in the next version of 4.x.x
