### ISSUE TITLE
o-form: Close insert form without confirmation

### ISSUE THREAD

**Issue by manuel-cid** [OntimizeWeb/ontimize-web-ngx#595]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
I have a table inside a form layout manager in **tab** mode. In the insert form I'm uploading a file and I want to close the *new* tab automatically by calling the method `closeDetail()` of the form, but a dialog appears that says I have unsaved change in the form (I'm using my own logic for uploading the file and some aditional data from different inputs in the form).

## Expected behavior
Attribute `confirm-exit="no"` in the insert form should work with form layout manager.

## Environment

<pre><code>
ontimize-web-ngx version: 8.2.4
</code></pre>

**Comment by patricia-martinez-imatia** [comment]
Also we detect that not work when it go other screen from a insert form inside a form layout manager in tab mode

**Comment by patricia-martinez-imatia** [comment]
The same thing happens when the form is not in a form-layout-manager and has the property after-insert-mode="close"
