### ISSUE TITLE
Implement virtual scroll in table component

### ISSUE THREAD

**Issue by manuel-cid** [OntimizeWeb/ontimize-web-ngx#596]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Expected behavior
Table component should use angular material's virtual scroll in order to increase performance.
Investigate the idea of integrating pagination and virtual scroll, check the following example
https://stackblitz.com/edit/mat-table-virtual-scroll-with-pagination

## Environment

<pre><code>
ontimize-web-ngx version: 8.x.x
</code></pre>

**Comment by patricia-martinez-imatia** [comment]
Duplicate issue
