### ISSUE TITLE
4.X - Problems showing data in ontimize-inputs

### ISSUE THREAD

**Issue by Fonsi20** [OntimizeWeb/ontimize-web-ngx#646]
## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
In our catalogue online, when we are navigated for the account profiles, the ontimize inputs, if the value dosent change, didn't appear.

## Expected behavior
We are in the first profile, and the field CREDIT is "YES", the o-text-input show "YES". If now we navegated to the profile 2 and the field credit still with a "YES" inside, the o-text-input dosen't show anything. We was trying to binding the data and still happends.

All this code is inside a o-form.

## Minimal reproduction of the problem with instructions
![image](https://user-images.githubusercontent.com/12035327/122892075-61af1380-d345-11eb-9210-c059cf6d0f13.png)
![image](https://user-images.githubusercontent.com/12035327/122892808-016ca180-d346-11eb-83f4-32d2959c6840.png)

## Environment

<pre><code>
ontimize-web-ngx version: 4.2.2-SNAPSHOT-4

Browser: <em>Check one of the following options with "x"</em>
- [ X ] Chrome (desktop) version 91.0.4472.106 (Build oficial) (64 bits)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 10.16.3
- Platform:  Windows

</code></pre>

**Comment by pacogomezimatia** [comment]
This problem was solved ussing _automatic-binding_ and _automatic-registering_ input for _o-text-input_.
