### ISSUE TITLE
Function setFieldValues not working fine on o-combo and o-list-picker

### ISSUE THREAD

**Issue by pacogomezimatia** [OntimizeWeb/ontimize-web-ngx#675]
You can help us process issues faster by providing the following information. Issues missing important information may be harder to resolve.

## I'm submitting a...
*Check one of the following options with "x"*
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  <em>Please search in other issues for a similar case before submitting</em>

[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead use [this](https://question2answer.imatia.com/)
</code></pre>

## Current behavior
Function setFieldValues not working fine on o-combo and o-list-picker.

## Expected behavior
To set field values in o-combo and o-list-picker using public function setFieldValues.

## Minimal reproduction of the problem with instructions
Use in a form with combo or list-picker:
_setFieldValues(this.data);_

## What is the motivation / use case for changing the behavior?
*Describe the motivation or the concrete use case*

## Environment

<pre><code>
ontimize-web-ngx version: 8.3.1

Browser: <em>Check one of the following options with "x"</em>
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

For Tooling issues:
- Node version: 12.10.0  <em>run `node --version`</em>
- Platform:  <em>Mac, Linux, Windows</em>

Others:
<em>Anything else relevant?  Operating system version, IDE, package manager, HTTP server, ...</em>

</code></pre>

**Comment by gonzalo-martinez-imt** [comment]
There is another possible problem, the setFieldValues function does not update the internal formData object in the o-form
