### ISSUE TITLE
bug o-form-layout-manager with mode="tab": when reload page, the text 'New' doesn't appear in the tab

### ISSUE THREAD

**Issue by patricia-martinez-imatia** [OntimizeWeb/ontimize-web-ngx#727]
### What is the current behavior?
If you have a page configured with an o-form-layout-manager with mode = "dialog" and you have opened a new tab, if you reload the page, the text 'New' does not appear

![image](https://user-images.githubusercontent.com/32088627/131329037-1d6437fa-0b98-41ea-847b-83dfc697f49b.png)

### Steps to reproduce
1. You should have a page configured with  a o-form-layout-manager with mode="tab"
2. Click New button
3. Reload page
4. It does not appear text 'New'

### Affected versions:
- `ontimize-web-ngx`: 8.4.1

**Comment by manuel-cid** [comment]
This error occurs when `navigationItems` is empty in `NavigationService`. Check `isInsertModePath` in `OFormComponent`
