### ISSUE TITLE
o-grid: display insert button with standard styling

### ISSUE THREAD

**Issue by manuel-cid** [OntimizeWeb/ontimize-web-ngx#787]
### Description
Add the ability to display the insert and refresh button in the toolbar with the same style than the buttons on the table or the form.
The component `o-grid` displays the insert button floating at the bottom, it would be nice to display it in the toolbar with differen configurations: icon, icon+text or text; the same behaviour we have in buttons of the the table of form.
This can be extended also to refresh button.

**Comment by patricia-martinez-imatia** [comment]
Hi, 
You can use `insert-button-floatable="no"` to display the button on the toolbar and `show-buttons-text` input to show/hide the button text

**Comment by manuel-cid** [comment]
Thanks! 😄
