### ISSUE TITLE
Error in doc of Toolbar

### ISSUE THREAD

**Issue by xaime-pardal-imatia** [OntimizeWeb/ontimize-web-ngx#837]
### Documentation

` "node_modules/flag-icon-css/css/flag-icon.css"` is misspelled, the correct name of the file is `"node_modules/flag-icon-css/css/flag-icons.css"` (with S). At least in the last version: 4.1.5

**Affected documentation page:** https://ontimizeweb.github.io/docs/components/applayout/overview section Toolbar.

**Comment by daniel-grana** [comment]
The typo was fixed. Thank you for reporting!
