### ISSUE TITLE
O-table: ediable table mode (insert-table="yes")

### ISSUE THREAD

**Issue by dr-mohamed-benkhalifa** [OntimizeWeb/ontimize-web-ngx#86]
When there are two or more tables in the same page, insert-table is active for all tables, when inserting rows in any of them, the other tables will have (n) additional blank row: n=number of rows added to edited table.

**Comment by gatsbimantico** [comment]
`insert-table` is no longer available, see breaking changes: https://github.com/OntimizeWeb/ontimize-web-ngx/blob/50c4ca22b0bf6377b92057c3a5037620cf9ddf9b/CHANGELOG.md#210-2018-03-15

Probably the new o-table-editable-row will solve this issue

**Comment by manu-cr** [comment]
There `o-table` inner component `o-table-insertable-row` is the responsible of this behaviour since [2.1.0](https://github.com/OntimizeWeb/ontimize-web-ngx/releases/tag/2.1.0)
