### ISSUE TITLE
o-image field "	magnifying glass" button usage

### ISSUE THREAD

**Issue by AngelFernandezF** [OntimizeWeb/ontimize-web-ngx#92]
o-image field has a "magnifying glass" button with a strange behaviour.
In read mode this button seems to do nothing.
In edit mode this button is sued to select the field related image from the hard drive.

Regarding this field, there is no way to open a detailed view or window with the image in a bigger size, which might be the logical functionality of the "magnifying glass" button.

**Comment by manu-cr** [comment]
Solved in https://github.com/OntimizeWeb/ontimize-web-ngx/commit/78bff44
