### ISSUE TITLE
app.config.ts: permissionsServiceType

### ISSUE THREAD

**Issue by patricia-martinez-imatia** [OntimizeWeb/ontimize-web-ngx#967]
### Description

Currently,  It is required configure in app.config.ts when you want to get the permissions data from server.
` 
...
permissionsServiceType:  'OntimizeEEPermissions,
permissionsConfiguration: { 
	     service: 'permissions'
},
...

',`

### Describe the solution you'd like
That it was not necessary to configure permissionsServieType and had a similar performance to **serviceType**

**Comment by daniel-grana** [comment]
We are going to change default value initialization of these two properties:
- serviceType -> OntmizeEE
- permissionsServiceType: OntimizeEEPermissions
Add Breaking change note into CHANGELOG
