### ISSUE TITLE
Review export features of table

### ISSUE THREAD

**Issue by daniel-grana** [OntimizeWeb/ontimize-web-ngx#993]
### Context
Check all the export features are working well with new OntimizeBoot backend services.

### Affected versions:
- `ontimize-web-ngx`: 8.7.0

**Comment by patricia-martinez-imatia** [comment]
Currently the default excel, pdf and html exports are not working

![Image](https://user-images.githubusercontent.com/32088627/177924154-29f85a82-d9ae-4caf-9aac-05d9835daed5.png)
